DROP TABLE IF EXISTS "IOUs" cascade;
DROP TABLE IF EXISTS "Lives" cascade;
CREATE TABLE "IOUs" ("fname" VARCHAR(20), "lname" VARCHAR(20), "amount" FLOAT);
CREATE TABLE "Lives" ( "fname" VARCHAR(20), "lname" VARCHAR(20), "city" VARCHAR(20));
INSERT INTO "IOUs" ("fname", "lname", "amount") VALUES ('Bob', 'Smith', 30);
INSERT INTO "IOUs" ("fname", "lname", "amount") VALUES ('Sue', 'Jones', 20);
INSERT INTO "IOUs" ("fname", "lname", "amount") VALUES ('Bob', 'Smith', 30);
INSERT INTO "Lives" ("fname", "lname", "city") VALUES ('Bob', 'Smith', 'London');
INSERT INTO "Lives" ("fname", "lname", "city") VALUES ('Sue', 'Jones', 'Madrid');
INSERT INTO "Lives" ("fname", "lname", "city") VALUES ('Bob', 'Smith', 'London');