__author__ = "Julián Arenas-Guerrero"
__license__ = "Apache-2.0"

"""R2RML namespace constants (http://www.w3.org/ns/r2rml#)."""

R2RML_NAMESPACE = "http://www.w3.org/ns/r2rml#"

# ── Classes ───────────────────────────────────────────────────────────────────
R2RML_BASE_TABLE_OR_VIEW_CLASS   = f"{R2RML_NAMESPACE}BaseTableOrView"
R2RML_GRAPH_MAP_CLASS            = f"{R2RML_NAMESPACE}GraphMap"
R2RML_JOIN_CLASS                 = f"{R2RML_NAMESPACE}Join"
R2RML_LOGICAL_TABLE_CLASS        = f"{R2RML_NAMESPACE}LogicalTable"
R2RML_OBJECT_MAP_CLASS           = f"{R2RML_NAMESPACE}ObjectMap"
R2RML_PREDICATE_MAP_CLASS        = f"{R2RML_NAMESPACE}PredicateMap"
R2RML_PREDICATE_OBJECT_MAP_CLASS = f"{R2RML_NAMESPACE}PredicateObjectMap"
R2RML_R2RML_VIEW_CLASS           = f"{R2RML_NAMESPACE}R2RMLView"
R2RML_REF_OBJECT_MAP_CLASS       = f"{R2RML_NAMESPACE}RefObjectMap"
R2RML_SUBJECT_MAP_CLASS          = f"{R2RML_NAMESPACE}SubjectMap"
R2RML_TERM_MAP_CLASS             = f"{R2RML_NAMESPACE}TermMap"
R2RML_TRIPLES_MAP_CLASS          = f"{R2RML_NAMESPACE}TriplesMap"

# ── Properties ────────────────────────────────────────────────────────────────
R2RML_LOGICAL_TABLE      = f"{R2RML_NAMESPACE}logicalTable"
R2RML_TABLE_NAME         = f"{R2RML_NAMESPACE}tableName"
R2RML_PARENT_TRIPLES_MAP = f"{R2RML_NAMESPACE}parentTriplesMap"
R2RML_SUBJECT_MAP        = f"{R2RML_NAMESPACE}subjectMap"
R2RML_PREDICATE_MAP      = f"{R2RML_NAMESPACE}predicateMap"
R2RML_OBJECT_MAP         = f"{R2RML_NAMESPACE}objectMap"
R2RML_GRAPH_MAP          = f"{R2RML_NAMESPACE}graphMap"
R2RML_PREDICATE_OBJECT_MAP = f"{R2RML_NAMESPACE}predicateObjectMap"
R2RML_SUBJECT_SHORTCUT   = f"{R2RML_NAMESPACE}subject"
R2RML_PREDICATE_SHORTCUT = f"{R2RML_NAMESPACE}predicate"
R2RML_OBJECT_SHORTCUT    = f"{R2RML_NAMESPACE}object"
R2RML_GRAPH_SHORTCUT     = f"{R2RML_NAMESPACE}graph"
R2RML_CONSTANT           = f"{R2RML_NAMESPACE}constant"
R2RML_TEMPLATE           = f"{R2RML_NAMESPACE}template"
R2RML_COLUMN             = f"{R2RML_NAMESPACE}column"
R2RML_CLASS              = f"{R2RML_NAMESPACE}class"
R2RML_CHILD              = f"{R2RML_NAMESPACE}child"
R2RML_PARENT             = f"{R2RML_NAMESPACE}parent"
R2RML_JOIN_CONDITION     = f"{R2RML_NAMESPACE}joinCondition"
R2RML_DATATYPE           = f"{R2RML_NAMESPACE}datatype"
R2RML_LANGUAGE           = f"{R2RML_NAMESPACE}language"
R2RML_SQL_QUERY          = f"{R2RML_NAMESPACE}sqlQuery"
R2RML_SQL_VERSION        = f"{R2RML_NAMESPACE}sqlVersion"
R2RML_TERM_TYPE          = f"{R2RML_NAMESPACE}termType"

# ── Other ─────────────────────────────────────────────────────────────────────
R2RML_DEFAULT_GRAPH = f"{R2RML_NAMESPACE}defaultGraph"
R2RML_IRI           = f"{R2RML_NAMESPACE}IRI"
R2RML_LITERAL       = f"{R2RML_NAMESPACE}Literal"
R2RML_BLANK_NODE    = f"{R2RML_NAMESPACE}BlankNode"
R2RML_SQL2008       = f"{R2RML_NAMESPACE}SQL2008"
